// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/mig/v0_1/mig.proto

package migv01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindingType int32

const (
	BindingType_BINDING_TYPE_UNSPECIFIED BindingType = 0
	BindingType_BINDING_TYPE_GRPC        BindingType = 1
	BindingType_BINDING_TYPE_NATS        BindingType = 2
	BindingType_BINDING_TYPE_HTTP        BindingType = 3
)

// Enum value maps for BindingType.
var (
	BindingType_name = map[int32]string{
		0: "BINDING_TYPE_UNSPECIFIED",
		1: "BINDING_TYPE_GRPC",
		2: "BINDING_TYPE_NATS",
		3: "BINDING_TYPE_HTTP",
	}
	BindingType_value = map[string]int32{
		"BINDING_TYPE_UNSPECIFIED": 0,
		"BINDING_TYPE_GRPC":        1,
		"BINDING_TYPE_NATS":        2,
		"BINDING_TYPE_HTTP":        3,
	}
)

func (x BindingType) Enum() *BindingType {
	p := new(BindingType)
	*p = x
	return p
}

func (x BindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mig_v0_1_mig_proto_enumTypes[0].Descriptor()
}

func (BindingType) Type() protoreflect.EnumType {
	return &file_proto_mig_v0_1_mig_proto_enumTypes[0]
}

func (x BindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingType.Descriptor instead.
func (BindingType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{0}
}

type InvocationMode int32

const (
	InvocationMode_INVOCATION_MODE_UNSPECIFIED   InvocationMode = 0
	InvocationMode_INVOCATION_MODE_UNARY         InvocationMode = 1
	InvocationMode_INVOCATION_MODE_SERVER_STREAM InvocationMode = 2
	InvocationMode_INVOCATION_MODE_CLIENT_STREAM InvocationMode = 3
	InvocationMode_INVOCATION_MODE_BIDI_STREAM   InvocationMode = 4
)

// Enum value maps for InvocationMode.
var (
	InvocationMode_name = map[int32]string{
		0: "INVOCATION_MODE_UNSPECIFIED",
		1: "INVOCATION_MODE_UNARY",
		2: "INVOCATION_MODE_SERVER_STREAM",
		3: "INVOCATION_MODE_CLIENT_STREAM",
		4: "INVOCATION_MODE_BIDI_STREAM",
	}
	InvocationMode_value = map[string]int32{
		"INVOCATION_MODE_UNSPECIFIED":   0,
		"INVOCATION_MODE_UNARY":         1,
		"INVOCATION_MODE_SERVER_STREAM": 2,
		"INVOCATION_MODE_CLIENT_STREAM": 3,
		"INVOCATION_MODE_BIDI_STREAM":   4,
	}
)

func (x InvocationMode) Enum() *InvocationMode {
	p := new(InvocationMode)
	*p = x
	return p
}

func (x InvocationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mig_v0_1_mig_proto_enumTypes[1].Descriptor()
}

func (InvocationMode) Type() protoreflect.EnumType {
	return &file_proto_mig_v0_1_mig_proto_enumTypes[1]
}

func (x InvocationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationMode.Descriptor instead.
func (InvocationMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{1}
}

type StreamPreference int32

const (
	StreamPreference_STREAM_PREFERENCE_UNSPECIFIED   StreamPreference = 0
	StreamPreference_STREAM_PREFERENCE_UNARY         StreamPreference = 1
	StreamPreference_STREAM_PREFERENCE_SERVER_STREAM StreamPreference = 2
	StreamPreference_STREAM_PREFERENCE_BIDI_STREAM   StreamPreference = 3
)

// Enum value maps for StreamPreference.
var (
	StreamPreference_name = map[int32]string{
		0: "STREAM_PREFERENCE_UNSPECIFIED",
		1: "STREAM_PREFERENCE_UNARY",
		2: "STREAM_PREFERENCE_SERVER_STREAM",
		3: "STREAM_PREFERENCE_BIDI_STREAM",
	}
	StreamPreference_value = map[string]int32{
		"STREAM_PREFERENCE_UNSPECIFIED":   0,
		"STREAM_PREFERENCE_UNARY":         1,
		"STREAM_PREFERENCE_SERVER_STREAM": 2,
		"STREAM_PREFERENCE_BIDI_STREAM":   3,
	}
)

func (x StreamPreference) Enum() *StreamPreference {
	p := new(StreamPreference)
	*p = x
	return p
}

func (x StreamPreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamPreference) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mig_v0_1_mig_proto_enumTypes[2].Descriptor()
}

func (StreamPreference) Type() protoreflect.EnumType {
	return &file_proto_mig_v0_1_mig_proto_enumTypes[2]
}

func (x StreamPreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamPreference.Descriptor instead.
func (StreamPreference) EnumDescriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{2}
}

type DeliverySemantics int32

const (
	DeliverySemantics_DELIVERY_SEMANTICS_UNSPECIFIED   DeliverySemantics = 0
	DeliverySemantics_DELIVERY_SEMANTICS_BEST_EFFORT   DeliverySemantics = 1
	DeliverySemantics_DELIVERY_SEMANTICS_AT_LEAST_ONCE DeliverySemantics = 2
	DeliverySemantics_DELIVERY_SEMANTICS_EXACTLY_ONCE  DeliverySemantics = 3
)

// Enum value maps for DeliverySemantics.
var (
	DeliverySemantics_name = map[int32]string{
		0: "DELIVERY_SEMANTICS_UNSPECIFIED",
		1: "DELIVERY_SEMANTICS_BEST_EFFORT",
		2: "DELIVERY_SEMANTICS_AT_LEAST_ONCE",
		3: "DELIVERY_SEMANTICS_EXACTLY_ONCE",
	}
	DeliverySemantics_value = map[string]int32{
		"DELIVERY_SEMANTICS_UNSPECIFIED":   0,
		"DELIVERY_SEMANTICS_BEST_EFFORT":   1,
		"DELIVERY_SEMANTICS_AT_LEAST_ONCE": 2,
		"DELIVERY_SEMANTICS_EXACTLY_ONCE":  3,
	}
)

func (x DeliverySemantics) Enum() *DeliverySemantics {
	p := new(DeliverySemantics)
	*p = x
	return p
}

func (x DeliverySemantics) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliverySemantics) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mig_v0_1_mig_proto_enumTypes[3].Descriptor()
}

func (DeliverySemantics) Type() protoreflect.EnumType {
	return &file_proto_mig_v0_1_mig_proto_enumTypes[3]
}

func (x DeliverySemantics) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliverySemantics.Descriptor instead.
func (DeliverySemantics) EnumDescriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{3}
}

type FrameKind int32

const (
	FrameKind_FRAME_KIND_UNSPECIFIED FrameKind = 0
	FrameKind_FRAME_KIND_REQUEST     FrameKind = 1
	FrameKind_FRAME_KIND_RESPONSE    FrameKind = 2
	FrameKind_FRAME_KIND_EVENT       FrameKind = 3
	FrameKind_FRAME_KIND_CONTROL     FrameKind = 4
	FrameKind_FRAME_KIND_ERROR       FrameKind = 5
)

// Enum value maps for FrameKind.
var (
	FrameKind_name = map[int32]string{
		0: "FRAME_KIND_UNSPECIFIED",
		1: "FRAME_KIND_REQUEST",
		2: "FRAME_KIND_RESPONSE",
		3: "FRAME_KIND_EVENT",
		4: "FRAME_KIND_CONTROL",
		5: "FRAME_KIND_ERROR",
	}
	FrameKind_value = map[string]int32{
		"FRAME_KIND_UNSPECIFIED": 0,
		"FRAME_KIND_REQUEST":     1,
		"FRAME_KIND_RESPONSE":    2,
		"FRAME_KIND_EVENT":       3,
		"FRAME_KIND_CONTROL":     4,
		"FRAME_KIND_ERROR":       5,
	}
)

func (x FrameKind) Enum() *FrameKind {
	p := new(FrameKind)
	*p = x
	return p
}

func (x FrameKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mig_v0_1_mig_proto_enumTypes[4].Descriptor()
}

func (FrameKind) Type() protoreflect.EnumType {
	return &file_proto_mig_v0_1_mig_proto_enumTypes[4]
}

func (x FrameKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameKind.Descriptor instead.
func (FrameKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{4}
}

type MigErrorCode int32

const (
	MigErrorCode_MIG_ERROR_CODE_UNSPECIFIED MigErrorCode = 0
	MigErrorCode_MIG_INVALID_REQUEST        MigErrorCode = 1
	MigErrorCode_MIG_UNAUTHORIZED           MigErrorCode = 2
	MigErrorCode_MIG_FORBIDDEN              MigErrorCode = 3
	MigErrorCode_MIG_NOT_FOUND              MigErrorCode = 4
	MigErrorCode_MIG_UNSUPPORTED_CAPABILITY MigErrorCode = 5
	MigErrorCode_MIG_VERSION_MISMATCH       MigErrorCode = 6
	MigErrorCode_MIG_TIMEOUT                MigErrorCode = 7
	MigErrorCode_MIG_RATE_LIMITED           MigErrorCode = 8
	MigErrorCode_MIG_BACKPRESSURE           MigErrorCode = 9
	MigErrorCode_MIG_UNAVAILABLE            MigErrorCode = 10
	MigErrorCode_MIG_INTERNAL               MigErrorCode = 11
)

// Enum value maps for MigErrorCode.
var (
	MigErrorCode_name = map[int32]string{
		0:  "MIG_ERROR_CODE_UNSPECIFIED",
		1:  "MIG_INVALID_REQUEST",
		2:  "MIG_UNAUTHORIZED",
		3:  "MIG_FORBIDDEN",
		4:  "MIG_NOT_FOUND",
		5:  "MIG_UNSUPPORTED_CAPABILITY",
		6:  "MIG_VERSION_MISMATCH",
		7:  "MIG_TIMEOUT",
		8:  "MIG_RATE_LIMITED",
		9:  "MIG_BACKPRESSURE",
		10: "MIG_UNAVAILABLE",
		11: "MIG_INTERNAL",
	}
	MigErrorCode_value = map[string]int32{
		"MIG_ERROR_CODE_UNSPECIFIED": 0,
		"MIG_INVALID_REQUEST":        1,
		"MIG_UNAUTHORIZED":           2,
		"MIG_FORBIDDEN":              3,
		"MIG_NOT_FOUND":              4,
		"MIG_UNSUPPORTED_CAPABILITY": 5,
		"MIG_VERSION_MISMATCH":       6,
		"MIG_TIMEOUT":                7,
		"MIG_RATE_LIMITED":           8,
		"MIG_BACKPRESSURE":           9,
		"MIG_UNAVAILABLE":            10,
		"MIG_INTERNAL":               11,
	}
)

func (x MigErrorCode) Enum() *MigErrorCode {
	p := new(MigErrorCode)
	*p = x
	return p
}

func (x MigErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mig_v0_1_mig_proto_enumTypes[5].Descriptor()
}

func (MigErrorCode) Type() protoreflect.EnumType {
	return &file_proto_mig_v0_1_mig_proto_enumTypes[5]
}

func (x MigErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigErrorCode.Descriptor instead.
func (MigErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{5}
}

type MessageHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MigVersion     string                 `protobuf:"bytes,1,opt,name=mig_version,json=migVersion,proto3" json:"mig_version,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TenantId       string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Traceparent    string                 `protobuf:"bytes,6,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	DeadlineMs     uint32                 `protobuf:"varint,8,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	// Namespaced metadata extensions. `idg.*` is reserved for product telemetry
	// and usage metering correlation.
	Meta          *structpb.Struct `protobuf:"bytes,9,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetMigVersion() string {
	if x != nil {
		return x.MigVersion
	}
	return ""
}

func (x *MessageHeader) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageHeader) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MessageHeader) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MessageHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MessageHeader) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *MessageHeader) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *MessageHeader) GetDeadlineMs() uint32 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *MessageHeader) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

type HelloRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Header            *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SupportedVersions []string               `protobuf:"bytes,2,rep,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	RequestedBindings []BindingType          `protobuf:"varint,3,rep,packed,name=requested_bindings,json=requestedBindings,proto3,enum=mig.v0_1.BindingType" json:"requested_bindings,omitempty"`
	RequestedFeatures []string               `protobuf:"bytes,4,rep,name=requested_features,json=requestedFeatures,proto3" json:"requested_features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HelloRequest) GetSupportedVersions() []string {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

func (x *HelloRequest) GetRequestedBindings() []BindingType {
	if x != nil {
		return x.RequestedBindings
	}
	return nil
}

func (x *HelloRequest) GetRequestedFeatures() []string {
	if x != nil {
		return x.RequestedFeatures
	}
	return nil
}

type HelloResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SelectedVersion string                 `protobuf:"bytes,2,opt,name=selected_version,json=selectedVersion,proto3" json:"selected_version,omitempty"`
	SelectedBinding BindingType            `protobuf:"varint,3,opt,name=selected_binding,json=selectedBinding,proto3,enum=mig.v0_1.BindingType" json:"selected_binding,omitempty"`
	EnabledFeatures []string               `protobuf:"bytes,4,rep,name=enabled_features,json=enabledFeatures,proto3" json:"enabled_features,omitempty"`
	ServerId        string                 `protobuf:"bytes,5,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HelloResponse) GetSelectedVersion() string {
	if x != nil {
		return x.SelectedVersion
	}
	return ""
}

func (x *HelloResponse) GetSelectedBinding() BindingType {
	if x != nil {
		return x.SelectedBinding
	}
	return BindingType_BINDING_TYPE_UNSPECIFIED
}

func (x *HelloResponse) GetEnabledFeatures() []string {
	if x != nil {
		return x.EnabledFeatures
	}
	return nil
}

func (x *HelloResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type DiscoverRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Header            *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Query             string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	IncludeSchemaRefs bool                   `protobuf:"varint,3,opt,name=include_schema_refs,json=includeSchemaRefs,proto3" json:"include_schema_refs,omitempty"`
	IncludeQos        bool                   `protobuf:"varint,4,opt,name=include_qos,json=includeQos,proto3" json:"include_qos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoverRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DiscoverRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DiscoverRequest) GetIncludeSchemaRefs() bool {
	if x != nil {
		return x.IncludeSchemaRefs
	}
	return false
}

func (x *DiscoverRequest) GetIncludeQos() bool {
	if x != nil {
		return x.IncludeQos
	}
	return false
}

type DiscoverResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Header        *MessageHeader          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Capabilities  []*CapabilityDescriptor `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverResponse) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DiscoverResponse) GetCapabilities() []*CapabilityDescriptor {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CapabilityDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Modes           []InvocationMode       `protobuf:"varint,3,rep,packed,name=modes,proto3,enum=mig.v0_1.InvocationMode" json:"modes,omitempty"`
	InputSchemaUri  string                 `protobuf:"bytes,4,opt,name=input_schema_uri,json=inputSchemaUri,proto3" json:"input_schema_uri,omitempty"`
	OutputSchemaUri string                 `protobuf:"bytes,5,opt,name=output_schema_uri,json=outputSchemaUri,proto3" json:"output_schema_uri,omitempty"`
	EventTopics     []string               `protobuf:"bytes,6,rep,name=event_topics,json=eventTopics,proto3" json:"event_topics,omitempty"`
	AuthScopes      []string               `protobuf:"bytes,7,rep,name=auth_scopes,json=authScopes,proto3" json:"auth_scopes,omitempty"`
	Qos             *QoSProfile            `protobuf:"bytes,8,opt,name=qos,proto3" json:"qos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilityDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CapabilityDescriptor) GetModes() []InvocationMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *CapabilityDescriptor) GetInputSchemaUri() string {
	if x != nil {
		return x.InputSchemaUri
	}
	return ""
}

func (x *CapabilityDescriptor) GetOutputSchemaUri() string {
	if x != nil {
		return x.OutputSchemaUri
	}
	return ""
}

func (x *CapabilityDescriptor) GetEventTopics() []string {
	if x != nil {
		return x.EventTopics
	}
	return nil
}

func (x *CapabilityDescriptor) GetAuthScopes() []string {
	if x != nil {
		return x.AuthScopes
	}
	return nil
}

func (x *CapabilityDescriptor) GetQos() *QoSProfile {
	if x != nil {
		return x.Qos
	}
	return nil
}

type QoSProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxPayloadBytes   uint64                 `protobuf:"varint,1,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	SupportsReplay    bool                   `protobuf:"varint,2,opt,name=supports_replay,json=supportsReplay,proto3" json:"supports_replay,omitempty"`
	DeliverySemantics DeliverySemantics      `protobuf:"varint,3,opt,name=delivery_semantics,json=deliverySemantics,proto3,enum=mig.v0_1.DeliverySemantics" json:"delivery_semantics,omitempty"`
	SupportsOrdering  bool                   `protobuf:"varint,4,opt,name=supports_ordering,json=supportsOrdering,proto3" json:"supports_ordering,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QoSProfile) Reset() {
	*x = QoSProfile{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QoSProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QoSProfile) ProtoMessage() {}

func (x *QoSProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QoSProfile.ProtoReflect.Descriptor instead.
func (*QoSProfile) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{6}
}

func (x *QoSProfile) GetMaxPayloadBytes() uint64 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

func (x *QoSProfile) GetSupportsReplay() bool {
	if x != nil {
		return x.SupportsReplay
	}
	return false
}

func (x *QoSProfile) GetDeliverySemantics() DeliverySemantics {
	if x != nil {
		return x.DeliverySemantics
	}
	return DeliverySemantics_DELIVERY_SEMANTICS_UNSPECIFIED
}

func (x *QoSProfile) GetSupportsOrdering() bool {
	if x != nil {
		return x.SupportsOrdering
	}
	return false
}

type InvokeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Header           *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Capability       string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Payload          *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	StreamPreference StreamPreference       `protobuf:"varint,4,opt,name=stream_preference,json=streamPreference,proto3,enum=mig.v0_1.StreamPreference" json:"stream_preference,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InvokeRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetStreamPreference() StreamPreference {
	if x != nil {
		return x.StreamPreference
	}
	return StreamPreference_STREAM_PREFERENCE_UNSPECIFIED
}

type InvokeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Capability      string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ResultSchemaUri string                 `protobuf:"bytes,4,opt,name=result_schema_uri,json=resultSchemaUri,proto3" json:"result_schema_uri,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeResponse) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InvokeResponse) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeResponse) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeResponse) GetResultSchemaUri() string {
	if x != nil {
		return x.ResultSchemaUri
	}
	return ""
}

type StreamFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Capability    string                 `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	Kind          FrameKind              `protobuf:"varint,4,opt,name=kind,proto3,enum=mig.v0_1.FrameKind" json:"kind,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	EndStream     bool                   `protobuf:"varint,6,opt,name=end_stream,json=endStream,proto3" json:"end_stream,omitempty"`
	Error         *MigError              `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{9}
}

func (x *StreamFrame) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StreamFrame) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamFrame) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *StreamFrame) GetKind() FrameKind {
	if x != nil {
		return x.Kind
	}
	return FrameKind_FRAME_KIND_UNSPECIFIED
}

func (x *StreamFrame) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamFrame) GetEndStream() bool {
	if x != nil {
		return x.EndStream
	}
	return false
}

func (x *StreamFrame) GetError() *MigError {
	if x != nil {
		return x.Error
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{10}
}

func (x *PublishRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Accepted      bool                   `protobuf:"varint,5,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAck) Reset() {
	*x = PublishAck{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAck) ProtoMessage() {}

func (x *PublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAck.ProtoReflect.Descriptor instead.
func (*PublishAck) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{11}
}

func (x *PublishAck) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PublishAck) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PublishAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ResumeCursor  string                 `protobuf:"bytes,4,opt,name=resume_cursor,json=resumeCursor,proto3" json:"resume_cursor,omitempty"`
	MaxInflight   uint32                 `protobuf:"varint,5,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *SubscribeRequest) GetResumeCursor() string {
	if x != nil {
		return x.ResumeCursor
	}
	return ""
}

func (x *SubscribeRequest) GetMaxInflight() uint32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Replay        bool                   `protobuf:"varint,7,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{13}
}

func (x *EventMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EventMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventMessage) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventMessage) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *EventMessage) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

type CancelRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TargetMessageId string                 `protobuf:"bytes,2,opt,name=target_message_id,json=targetMessageId,proto3" json:"target_message_id,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{14}
}

func (x *CancelRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelRequest) GetTargetMessageId() string {
	if x != nil {
		return x.TargetMessageId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TargetMessageId string                 `protobuf:"bytes,2,opt,name=target_message_id,json=targetMessageId,proto3" json:"target_message_id,omitempty"`
	Accepted        bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelAck) Reset() {
	*x = CancelAck{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAck) ProtoMessage() {}

func (x *CancelAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAck.ProtoReflect.Descriptor instead.
func (*CancelAck) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{15}
}

func (x *CancelAck) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelAck) GetTargetMessageId() string {
	if x != nil {
		return x.TargetMessageId
	}
	return ""
}

func (x *CancelAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CancelAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IntervalMs    uint32                 `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatRequest) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HeartbeatRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type HeartbeatAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Header              *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SuggestedIntervalMs uint32                 `protobuf:"varint,2,opt,name=suggested_interval_ms,json=suggestedIntervalMs,proto3" json:"suggested_interval_ms,omitempty"`
	LoadFactor          float64                `protobuf:"fixed64,3,opt,name=load_factor,json=loadFactor,proto3" json:"load_factor,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatAck) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HeartbeatAck) GetSuggestedIntervalMs() uint32 {
	if x != nil {
		return x.SuggestedIntervalMs
	}
	return 0
}

func (x *HeartbeatAck) GetLoadFactor() float64 {
	if x != nil {
		return x.LoadFactor
	}
	return 0
}

type MigError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          MigErrorCode           `protobuf:"varint,1,opt,name=code,proto3,enum=mig.v0_1.MigErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigError) Reset() {
	*x = MigError{}
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigError) ProtoMessage() {}

func (x *MigError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mig_v0_1_mig_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigError.ProtoReflect.Descriptor instead.
func (*MigError) Descriptor() ([]byte, []int) {
	return file_proto_mig_v0_1_mig_proto_rawDescGZIP(), []int{18}
}

func (x *MigError) GetCode() MigErrorCode {
	if x != nil {
		return x.Code
	}
	return MigErrorCode_MIG_ERROR_CODE_UNSPECIFIED
}

func (x *MigError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MigError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *MigError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_mig_v0_1_mig_proto protoreflect.FileDescriptor

const file_proto_mig_v0_1_mig_proto_rawDesc = "" +
	"\n" +
	"\x18proto/mig/v0_1/mig.proto\x12\bmig.v0_1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x02\n" +
	"\rMessageHeader\x12\x1f\n" +
	"\vmig_version\x18\x01 \x01(\tR\n" +
	"migVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12 \n" +
	"\vtraceparent\x18\x06 \x01(\tR\vtraceparent\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\vdeadline_ms\x18\b \x01(\rR\n" +
	"deadlineMs\x12+\n" +
	"\x04meta\x18\t \x01(\v2\x17.google.protobuf.StructR\x04meta\"\xe3\x01\n" +
	"\fHelloRequest\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12-\n" +
	"\x12supported_versions\x18\x02 \x03(\tR\x11supportedVersions\x12D\n" +
	"\x12requested_bindings\x18\x03 \x03(\x0e2\x15.mig.v0_1.BindingTypeR\x11requestedBindings\x12-\n" +
	"\x12requested_features\x18\x04 \x03(\tR\x11requestedFeatures\"\xf5\x01\n" +
	"\rHelloResponse\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12)\n" +
	"\x10selected_version\x18\x02 \x01(\tR\x0fselectedVersion\x12@\n" +
	"\x10selected_binding\x18\x03 \x01(\x0e2\x15.mig.v0_1.BindingTypeR\x0fselectedBinding\x12)\n" +
	"\x10enabled_features\x18\x04 \x03(\tR\x0fenabledFeatures\x12\x1b\n" +
	"\tserver_id\x18\x05 \x01(\tR\bserverId\"\xa9\x01\n" +
	"\x0fDiscoverRequest\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12.\n" +
	"\x13include_schema_refs\x18\x03 \x01(\bR\x11includeSchemaRefs\x12\x1f\n" +
	"\vinclude_qos\x18\x04 \x01(\bR\n" +
	"includeQos\"\x87\x01\n" +
	"\x10DiscoverResponse\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12B\n" +
	"\fcapabilities\x18\x02 \x03(\v2\x1e.mig.v0_1.CapabilityDescriptorR\fcapabilities\"\xb2\x02\n" +
	"\x14CapabilityDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12.\n" +
	"\x05modes\x18\x03 \x03(\x0e2\x18.mig.v0_1.InvocationModeR\x05modes\x12(\n" +
	"\x10input_schema_uri\x18\x04 \x01(\tR\x0einputSchemaUri\x12*\n" +
	"\x11output_schema_uri\x18\x05 \x01(\tR\x0foutputSchemaUri\x12!\n" +
	"\fevent_topics\x18\x06 \x03(\tR\veventTopics\x12\x1f\n" +
	"\vauth_scopes\x18\a \x03(\tR\n" +
	"authScopes\x12&\n" +
	"\x03qos\x18\b \x01(\v2\x14.mig.v0_1.QoSProfileR\x03qos\"\xda\x01\n" +
	"\n" +
	"QoSProfile\x12*\n" +
	"\x11max_payload_bytes\x18\x01 \x01(\x04R\x0fmaxPayloadBytes\x12'\n" +
	"\x0fsupports_replay\x18\x02 \x01(\bR\x0esupportsReplay\x12J\n" +
	"\x12delivery_semantics\x18\x03 \x01(\x0e2\x1b.mig.v0_1.DeliverySemanticsR\x11deliverySemantics\x12+\n" +
	"\x11supports_ordering\x18\x04 \x01(\bR\x10supportsOrdering\"\xdc\x01\n" +
	"\rInvokeRequest\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12G\n" +
	"\x11stream_preference\x18\x04 \x01(\x0e2\x1a.mig.v0_1.StreamPreferenceR\x10streamPreference\"\xc0\x01\n" +
	"\x0eInvokeResponse\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12*\n" +
	"\x11result_schema_uri\x18\x04 \x01(\tR\x0fresultSchemaUri\"\xa0\x02\n" +
	"\vStreamFrame\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x12'\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x13.mig.v0_1.FrameKindR\x04kind\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1d\n" +
	"\n" +
	"end_stream\x18\x06 \x01(\bR\tendStream\x12(\n" +
	"\x05error\x18\a \x01(\v2\x12.mig.v0_1.MigErrorR\x05error\"\x9c\x01\n" +
	"\x0ePublishRequest\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\"\xa6\x01\n" +
	"\n" +
	"PublishAck\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x1a\n" +
	"\baccepted\x18\x05 \x01(\bR\baccepted\"\xc2\x01\n" +
	"\x10SubscribeRequest\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rresume_cursor\x18\x04 \x01(\tR\fresumeCursor\x12!\n" +
	"\fmax_inflight\x18\x05 \x01(\rR\vmaxInflight\"\x96\x02\n" +
	"\fEventMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x16\n" +
	"\x06replay\x18\a \x01(\bR\x06replay\"\x84\x01\n" +
	"\rCancelRequest\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12*\n" +
	"\x11target_message_id\x18\x02 \x01(\tR\x0ftargetMessageId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9c\x01\n" +
	"\tCancelAck\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12*\n" +
	"\x11target_message_id\x18\x02 \x01(\tR\x0ftargetMessageId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"d\n" +
	"\x10HeartbeatRequest\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\rR\n" +
	"intervalMs\"\x94\x01\n" +
	"\fHeartbeatAck\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.mig.v0_1.MessageHeaderR\x06header\x122\n" +
	"\x15suggested_interval_ms\x18\x02 \x01(\rR\x13suggestedIntervalMs\x12\x1f\n" +
	"\vload_factor\x18\x03 \x01(\x01R\n" +
	"loadFactor\"\xa1\x01\n" +
	"\bMigError\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.mig.v0_1.MigErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x121\n" +
	"\adetails\x18\x04 \x01(\v2\x17.google.protobuf.StructR\adetails*p\n" +
	"\vBindingType\x12\x1c\n" +
	"\x18BINDING_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BINDING_TYPE_GRPC\x10\x01\x12\x15\n" +
	"\x11BINDING_TYPE_NATS\x10\x02\x12\x15\n" +
	"\x11BINDING_TYPE_HTTP\x10\x03*\xb3\x01\n" +
	"\x0eInvocationMode\x12\x1f\n" +
	"\x1bINVOCATION_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15INVOCATION_MODE_UNARY\x10\x01\x12!\n" +
	"\x1dINVOCATION_MODE_SERVER_STREAM\x10\x02\x12!\n" +
	"\x1dINVOCATION_MODE_CLIENT_STREAM\x10\x03\x12\x1f\n" +
	"\x1bINVOCATION_MODE_BIDI_STREAM\x10\x04*\x9a\x01\n" +
	"\x10StreamPreference\x12!\n" +
	"\x1dSTREAM_PREFERENCE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STREAM_PREFERENCE_UNARY\x10\x01\x12#\n" +
	"\x1fSTREAM_PREFERENCE_SERVER_STREAM\x10\x02\x12!\n" +
	"\x1dSTREAM_PREFERENCE_BIDI_STREAM\x10\x03*\xa6\x01\n" +
	"\x11DeliverySemantics\x12\"\n" +
	"\x1eDELIVERY_SEMANTICS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDELIVERY_SEMANTICS_BEST_EFFORT\x10\x01\x12$\n" +
	" DELIVERY_SEMANTICS_AT_LEAST_ONCE\x10\x02\x12#\n" +
	"\x1fDELIVERY_SEMANTICS_EXACTLY_ONCE\x10\x03*\x9c\x01\n" +
	"\tFrameKind\x12\x1a\n" +
	"\x16FRAME_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FRAME_KIND_REQUEST\x10\x01\x12\x17\n" +
	"\x13FRAME_KIND_RESPONSE\x10\x02\x12\x14\n" +
	"\x10FRAME_KIND_EVENT\x10\x03\x12\x16\n" +
	"\x12FRAME_KIND_CONTROL\x10\x04\x12\x14\n" +
	"\x10FRAME_KIND_ERROR\x10\x05*\xa1\x02\n" +
	"\fMigErrorCode\x12\x1e\n" +
	"\x1aMIG_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MIG_INVALID_REQUEST\x10\x01\x12\x14\n" +
	"\x10MIG_UNAUTHORIZED\x10\x02\x12\x11\n" +
	"\rMIG_FORBIDDEN\x10\x03\x12\x11\n" +
	"\rMIG_NOT_FOUND\x10\x04\x12\x1e\n" +
	"\x1aMIG_UNSUPPORTED_CAPABILITY\x10\x05\x12\x18\n" +
	"\x14MIG_VERSION_MISMATCH\x10\x06\x12\x0f\n" +
	"\vMIG_TIMEOUT\x10\a\x12\x14\n" +
	"\x10MIG_RATE_LIMITED\x10\b\x12\x14\n" +
	"\x10MIG_BACKPRESSURE\x10\t\x12\x13\n" +
	"\x0fMIG_UNAVAILABLE\x10\n" +
	"\x12\x10\n" +
	"\fMIG_INTERNAL\x10\v2\x88\x01\n" +
	"\tDiscovery\x128\n" +
	"\x05Hello\x12\x16.mig.v0_1.HelloRequest\x1a\x17.mig.v0_1.HelloResponse\x12A\n" +
	"\bDiscover\x12\x19.mig.v0_1.DiscoverRequest\x1a\x1a.mig.v0_1.DiscoverResponse2\x8b\x01\n" +
	"\n" +
	"Invocation\x12;\n" +
	"\x06Invoke\x12\x17.mig.v0_1.InvokeRequest\x1a\x18.mig.v0_1.InvokeResponse\x12@\n" +
	"\fStreamInvoke\x12\x15.mig.v0_1.StreamFrame\x1a\x15.mig.v0_1.StreamFrame(\x010\x012\x86\x01\n" +
	"\x06Events\x129\n" +
	"\aPublish\x12\x18.mig.v0_1.PublishRequest\x1a\x14.mig.v0_1.PublishAck\x12A\n" +
	"\tSubscribe\x12\x1a.mig.v0_1.SubscribeRequest\x1a\x16.mig.v0_1.EventMessage0\x012\x82\x01\n" +
	"\aControl\x126\n" +
	"\x06Cancel\x12\x17.mig.v0_1.CancelRequest\x1a\x13.mig.v0_1.CancelAck\x12?\n" +
	"\tHeartbeat\x12\x1a.mig.v0_1.HeartbeatRequest\x1a\x16.mig.v0_1.HeartbeatAckBB\n" +
	"\vio.mig.v0_1P\x01Z1github.com/mig-standard/mig/proto/mig/v0_1;migv01b\x06proto3"

var (
	file_proto_mig_v0_1_mig_proto_rawDescOnce sync.Once
	file_proto_mig_v0_1_mig_proto_rawDescData []byte
)

func file_proto_mig_v0_1_mig_proto_rawDescGZIP() []byte {
	file_proto_mig_v0_1_mig_proto_rawDescOnce.Do(func() {
		file_proto_mig_v0_1_mig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mig_v0_1_mig_proto_rawDesc), len(file_proto_mig_v0_1_mig_proto_rawDesc)))
	})
	return file_proto_mig_v0_1_mig_proto_rawDescData
}

var file_proto_mig_v0_1_mig_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_mig_v0_1_mig_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_mig_v0_1_mig_proto_goTypes = []any{
	(BindingType)(0),              // 0: mig.v0_1.BindingType
	(InvocationMode)(0),           // 1: mig.v0_1.InvocationMode
	(StreamPreference)(0),         // 2: mig.v0_1.StreamPreference
	(DeliverySemantics)(0),        // 3: mig.v0_1.DeliverySemantics
	(FrameKind)(0),                // 4: mig.v0_1.FrameKind
	(MigErrorCode)(0),             // 5: mig.v0_1.MigErrorCode
	(*MessageHeader)(nil),         // 6: mig.v0_1.MessageHeader
	(*HelloRequest)(nil),          // 7: mig.v0_1.HelloRequest
	(*HelloResponse)(nil),         // 8: mig.v0_1.HelloResponse
	(*DiscoverRequest)(nil),       // 9: mig.v0_1.DiscoverRequest
	(*DiscoverResponse)(nil),      // 10: mig.v0_1.DiscoverResponse
	(*CapabilityDescriptor)(nil),  // 11: mig.v0_1.CapabilityDescriptor
	(*QoSProfile)(nil),            // 12: mig.v0_1.QoSProfile
	(*InvokeRequest)(nil),         // 13: mig.v0_1.InvokeRequest
	(*InvokeResponse)(nil),        // 14: mig.v0_1.InvokeResponse
	(*StreamFrame)(nil),           // 15: mig.v0_1.StreamFrame
	(*PublishRequest)(nil),        // 16: mig.v0_1.PublishRequest
	(*PublishAck)(nil),            // 17: mig.v0_1.PublishAck
	(*SubscribeRequest)(nil),      // 18: mig.v0_1.SubscribeRequest
	(*EventMessage)(nil),          // 19: mig.v0_1.EventMessage
	(*CancelRequest)(nil),         // 20: mig.v0_1.CancelRequest
	(*CancelAck)(nil),             // 21: mig.v0_1.CancelAck
	(*HeartbeatRequest)(nil),      // 22: mig.v0_1.HeartbeatRequest
	(*HeartbeatAck)(nil),          // 23: mig.v0_1.HeartbeatAck
	(*MigError)(nil),              // 24: mig.v0_1.MigError
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 26: google.protobuf.Struct
}
var file_proto_mig_v0_1_mig_proto_depIdxs = []int32{
	25, // 0: mig.v0_1.MessageHeader.timestamp:type_name -> google.protobuf.Timestamp
	26, // 1: mig.v0_1.MessageHeader.meta:type_name -> google.protobuf.Struct
	6,  // 2: mig.v0_1.HelloRequest.header:type_name -> mig.v0_1.MessageHeader
	0,  // 3: mig.v0_1.HelloRequest.requested_bindings:type_name -> mig.v0_1.BindingType
	6,  // 4: mig.v0_1.HelloResponse.header:type_name -> mig.v0_1.MessageHeader
	0,  // 5: mig.v0_1.HelloResponse.selected_binding:type_name -> mig.v0_1.BindingType
	6,  // 6: mig.v0_1.DiscoverRequest.header:type_name -> mig.v0_1.MessageHeader
	6,  // 7: mig.v0_1.DiscoverResponse.header:type_name -> mig.v0_1.MessageHeader
	11, // 8: mig.v0_1.DiscoverResponse.capabilities:type_name -> mig.v0_1.CapabilityDescriptor
	1,  // 9: mig.v0_1.CapabilityDescriptor.modes:type_name -> mig.v0_1.InvocationMode
	12, // 10: mig.v0_1.CapabilityDescriptor.qos:type_name -> mig.v0_1.QoSProfile
	3,  // 11: mig.v0_1.QoSProfile.delivery_semantics:type_name -> mig.v0_1.DeliverySemantics
	6,  // 12: mig.v0_1.InvokeRequest.header:type_name -> mig.v0_1.MessageHeader
	26, // 13: mig.v0_1.InvokeRequest.payload:type_name -> google.protobuf.Struct
	2,  // 14: mig.v0_1.InvokeRequest.stream_preference:type_name -> mig.v0_1.StreamPreference
	6,  // 15: mig.v0_1.InvokeResponse.header:type_name -> mig.v0_1.MessageHeader
	26, // 16: mig.v0_1.InvokeResponse.payload:type_name -> google.protobuf.Struct
	6,  // 17: mig.v0_1.StreamFrame.header:type_name -> mig.v0_1.MessageHeader
	4,  // 18: mig.v0_1.StreamFrame.kind:type_name -> mig.v0_1.FrameKind
	26, // 19: mig.v0_1.StreamFrame.payload:type_name -> google.protobuf.Struct
	24, // 20: mig.v0_1.StreamFrame.error:type_name -> mig.v0_1.MigError
	6,  // 21: mig.v0_1.PublishRequest.header:type_name -> mig.v0_1.MessageHeader
	26, // 22: mig.v0_1.PublishRequest.payload:type_name -> google.protobuf.Struct
	6,  // 23: mig.v0_1.PublishAck.header:type_name -> mig.v0_1.MessageHeader
	6,  // 24: mig.v0_1.SubscribeRequest.header:type_name -> mig.v0_1.MessageHeader
	6,  // 25: mig.v0_1.EventMessage.header:type_name -> mig.v0_1.MessageHeader
	26, // 26: mig.v0_1.EventMessage.payload:type_name -> google.protobuf.Struct
	25, // 27: mig.v0_1.EventMessage.published_at:type_name -> google.protobuf.Timestamp
	6,  // 28: mig.v0_1.CancelRequest.header:type_name -> mig.v0_1.MessageHeader
	6,  // 29: mig.v0_1.CancelAck.header:type_name -> mig.v0_1.MessageHeader
	6,  // 30: mig.v0_1.HeartbeatRequest.header:type_name -> mig.v0_1.MessageHeader
	6,  // 31: mig.v0_1.HeartbeatAck.header:type_name -> mig.v0_1.MessageHeader
	5,  // 32: mig.v0_1.MigError.code:type_name -> mig.v0_1.MigErrorCode
	26, // 33: mig.v0_1.MigError.details:type_name -> google.protobuf.Struct
	7,  // 34: mig.v0_1.Discovery.Hello:input_type -> mig.v0_1.HelloRequest
	9,  // 35: mig.v0_1.Discovery.Discover:input_type -> mig.v0_1.DiscoverRequest
	13, // 36: mig.v0_1.Invocation.Invoke:input_type -> mig.v0_1.InvokeRequest
	15, // 37: mig.v0_1.Invocation.StreamInvoke:input_type -> mig.v0_1.StreamFrame
	16, // 38: mig.v0_1.Events.Publish:input_type -> mig.v0_1.PublishRequest
	18, // 39: mig.v0_1.Events.Subscribe:input_type -> mig.v0_1.SubscribeRequest
	20, // 40: mig.v0_1.Control.Cancel:input_type -> mig.v0_1.CancelRequest
	22, // 41: mig.v0_1.Control.Heartbeat:input_type -> mig.v0_1.HeartbeatRequest
	8,  // 42: mig.v0_1.Discovery.Hello:output_type -> mig.v0_1.HelloResponse
	10, // 43: mig.v0_1.Discovery.Discover:output_type -> mig.v0_1.DiscoverResponse
	14, // 44: mig.v0_1.Invocation.Invoke:output_type -> mig.v0_1.InvokeResponse
	15, // 45: mig.v0_1.Invocation.StreamInvoke:output_type -> mig.v0_1.StreamFrame
	17, // 46: mig.v0_1.Events.Publish:output_type -> mig.v0_1.PublishAck
	19, // 47: mig.v0_1.Events.Subscribe:output_type -> mig.v0_1.EventMessage
	21, // 48: mig.v0_1.Control.Cancel:output_type -> mig.v0_1.CancelAck
	23, // 49: mig.v0_1.Control.Heartbeat:output_type -> mig.v0_1.HeartbeatAck
	42, // [42:50] is the sub-list for method output_type
	34, // [34:42] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_proto_mig_v0_1_mig_proto_init() }
func file_proto_mig_v0_1_mig_proto_init() {
	if File_proto_mig_v0_1_mig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mig_v0_1_mig_proto_rawDesc), len(file_proto_mig_v0_1_mig_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_mig_v0_1_mig_proto_goTypes,
		DependencyIndexes: file_proto_mig_v0_1_mig_proto_depIdxs,
		EnumInfos:         file_proto_mig_v0_1_mig_proto_enumTypes,
		MessageInfos:      file_proto_mig_v0_1_mig_proto_msgTypes,
	}.Build()
	File_proto_mig_v0_1_mig_proto = out.File
	file_proto_mig_v0_1_mig_proto_goTypes = nil
	file_proto_mig_v0_1_mig_proto_depIdxs = nil
}
